services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NBI_URL=https://10.255.32.88:9999/osm
      - KUBECTL_COMMAND=/usr/local/bin/kubectl
      - KUBECTL_CONFIG_PATH=kube_config
      - UPDATE_CONTAINER_IDS_FREQ=5